# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compas_buff/data/element.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'compas_buff/data/element.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compas_buff.data import frame_pb2 as compas__buff_dot_data_dot_frame__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ompas_buff/data/element.proto\x12\x10\x63ompas_buff.data\x1a\x1c\x63ompas_buff/data/frame.proto\"\x82\x01\n\x0b\x45lementData\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x05\x66rame\x18\x03 \x01(\x0b\x32\x1b.compas_buff.data.FrameData\x12\r\n\x05xsize\x18\x04 \x01(\x02\x12\r\n\x05ysize\x18\x05 \x01(\x02\x12\r\n\x05zsize\x18\x06 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compas_buff.data.element_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELEMENTDATA']._serialized_start=83
  _globals['_ELEMENTDATA']._serialized_end=213
# @@protoc_insertion_point(module_scope)
