# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compas_buff/data/frame.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'compas_buff/data/frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from compas_buff.data import point_pb2 as compas__buff_dot_data_dot_point__pb2
from compas_buff.data import vector_pb2 as compas__buff_dot_data_dot_vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ompas_buff/data/frame.proto\x12\x10\x63ompas_buff.data\x1a\x1c\x63ompas_buff/data/point.proto\x1a\x1d\x63ompas_buff/data/vector.proto\"\xad\x01\n\tFrameData\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x05point\x18\x03 \x01(\x0b\x32\x1b.compas_buff.data.PointData\x12+\n\x05xaxis\x18\x04 \x01(\x0b\x32\x1c.compas_buff.data.VectorData\x12+\n\x05yaxis\x18\x05 \x01(\x0b\x32\x1c.compas_buff.data.VectorDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compas_buff.data.frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEDATA']._serialized_start=112
  _globals['_FRAMEDATA']._serialized_end=285
# @@protoc_insertion_point(module_scope)
